version: "3.9"
services:
  leader:
    volumes:
      - leader_volume:/home/boxer/volumes/leader
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ROLE=LEADER
      # TODO: Abstract the ports into variables, and dynamically create this env variable based on the ports
      - REPLICATION_NODES=http://localhost:8081
      - QUORUM_SIZE=2
      - LOG_FILE=./tmp/wal.log

  follower_one:
    build: .
    ports:
      - "8081:8080"
    environment:
      - NODE_ROLE=FOLLOWER
      - LOG_FILE=./tmp/wal.log
    volumes:
      - follower_one_vol:/home/boxer/volumes/leader

volumes:
  leader_volume:
    driver: local
  follower_one_vol:
    driver: local
