version: "3.9"

volumes:
  leader_volume:
    driver: local
  follower_one_vol:
    driver: local
  follower_two_vol:
    driver: local
  follower_three_vol:
    driver: local

services:
  leader:
    volumes:
      - leader_volume:/home/boxer/volumes/leader
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ROLE=LEADER
      # TODO: Abstract the ports into variables, and dynamically create this env variable based on the ports
      - REPLICATION_NODES=http://follower_one:8080,http://follower_two:8080,http://follower_three:8080
      - QUORUM_SIZE=2
      - LOG_FILE=./tmp/wal.log

  follower_one:
    build: .
    ports:
      - "8081:8080"
    environment:
      - NODE_ROLE=FOLLOWER
      - LOG_FILE=./tmp/wal.log
    volumes:
      - follower_one_vol:/home/boxer/volumes/follower_one

  follower_two:
    build: .
    ports:
      - "8082:8080"
    environment:
      - NODE_ROLE=FOLLOWER
      - LOG_FILE=./tmp/wal.log
    volumes:
      - follower_two_vol:/home/boxer/volumes/follower_two

  follower_three:
    build: .
    ports:
      - "8083:8080"
    environment:
      - NODE_ROLE=FOLLOWER
      - LOG_FILE=./tmp/wal.log
    volumes:
      - follower_three_vol:/home/boxer/volumes/follower_three
